### ISSUE TITLE
Question:  Umbraco 14 support

### ISSUE THREAD

**Issue by lakesol** [rickbutterfield/Our.Umbraco.BlockPreview#53]
### Feature summary

Hi,

I am new to this project and I am really impressed.  But I have a couple of questions before making the final decision to use this great project or go down the custom written view route.

1.  Where do the maintainers/supporters of the project see the roadmap of the project going?  e.g. any major new features/blockers in the future?
2. How quickly does support for new Umbraco versions get added to this project?
3. With the upcoming Umbraco 14 with Angular being dropped, do you see this being a hurdle/blocker for this project (My guess is that this project will make the transition to v14 easier)?

Many thanks

**Comment by rickbutterfield** [comment]
Hi @lakesol, appreciate the questions!

1. There currently isn't any sort of major roadmap outside of Umbraco 14 support, as I'd like this to be a fairly simple package that extends the core rather than do anything too complex. I am completely open to suggestions/PRs though if you think there is something key that's missing
2. Umbraco 14 support is currently underway! I'm working in the open in the [`feature/umbraco-14`](https://github.com/rickbutterfield/Umbraco.Community.BlockPreview/tree/feature/umbraco-14) branch and updating as quicky as I can when new betas are released. I have the code locally for beta003 working but haven't pushed it yet.
3. I don't see dropping Angular as a blocker, as I will simply need to create a WebComponent that streams the HTML in from the server, which should be relatively easy. The complexity with this currently is that v14 beta003 has only just added support for Block Grid and List working correctly (the ability to add and view blocks in the backoffice), and Custom Views aren't currently supported. Niels on the Umbraco FE team has explained generally how the Custom Views are going to work going forwards [(see Discord for the full chat)](https://discord.com/channels/869656431308189746/1227916075144974397/1227947538737397780):
> 'Custom Views' is still not a feature of v.14, it will come at one point 🤹 . But to spark your interest — enligthen you on where its heading. Then it will become Web Components and it will be established via Extension Manifests, so the idea is that they will no longer be something you pick via configuration UI. But instead a Extension Type which gets configured to which Blocks it should appear at. Thats the concept so far.

Hope that's all helpful 😄

**Comment by lakesol** [comment]
@rickbutterfield Many thanks for the full answer.  Much appreciated.  I am looking forward to seeing the progress on Umbarco 14 and this module.

Thanks 👍
